name: Python CI

run-name: Python CI by ${{ github.actor }} for ${{ github.sha }}

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  python-ci:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: "3.11"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: pip install -r src/requirements.txt coverage flake8

      - name: Generate coverage
        working-directory: src
        run: coverage run manage.py test

      - name: Show coverage report
        working-directory: src
        run: coverage report

      - name: Check code style
        working-directory: src
        continue-on-error: true
        run: flake8 . --extend-ignore=C901

      - name: Check code complexity
        working-directory: src
        continue-on-error: true
        run: flake8 . --max-complexity=10 --select=C901

      - name: Upload Python code
        uses: actions/upload-artifact@v4
        with:
          name: python-code
          path: |
            src/**/*.py
